version: '3'

services:
  builder:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: mvn clean package -DskipTests

  tomcat:
    image: tomcat:9.0-jre8-alpine
    depends_on:
      - builder
    ports:
      - '8080:8080'
    volumes:
      - ./target:/usr/local/tomcat/webapps
    command: >
      sh -c "cp /usr/local/tomcat/webapps/*.war /usr/local/tomcat/webapps/ROOT.war && catalina.sh run"

